version: '3'

services:
  bet_maker:
    build:
      context: ./bet_maker
      dockerfile: Dockerfile
    volumes:
      - ./bet_maker/app:/app
    restart: on-failure
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:qwerty@db:5432/aidar

  line_provider:
    build:
      context: ./line_provider
      dockerfile: Dockerfile
    volumes:
      - ./line_provider/app:/app
    restart: on-failure
    ports:
      - 8001:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:qwerty@db:5432/aidar

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - postgresql-user:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgresql-user:
